<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>name</key>
        <string>latex</string>
        <key>scopeName</key>
        <string>source.latex</string>
        <key>fileTypes</key>
        <array>
            <string></string>
        </array>
        <key>foldingStartMarker</key>
        <string></string>
        <key>foldingStopMarker</key>
        <string></string>
        <key>patterns</key>
        <array>
            <dict>
                <key>include</key>
                <string>#comment</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#special</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#parameter</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#command</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#math</string>
            </dict>
        </array>
        <key>repository</key>
        <dict>
            <key>comment</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>comment.line.latex</string>
                        <key>match</key>
                        <string>%.*$</string>
                    </dict>
                </array>
            </dict>
            <key>special</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>keyword.special.latex</string>
                        <key>match</key>
                        <string>[&amp;~]</string>
                    </dict>
                </array>
            </dict>
            <key>parameter</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.parameter.latex</string>
                        <key>match</key>
                        <string>#[0-9]</string>
                    </dict>
                </array>
            </dict>
            <key>command</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>(\\begin)\{((?:align|alignat|aligned|alignedat|array|Bmatrix|bmatrix|cases|CD|eqnarray|equation|gather|gathered|matrix|multline|pmatrix|smallmatrix|split|subarray|Vmatrix|vmatrix)\*?)\}</string>
                        <key>end</key>
                        <string>(\\end)\{((?:align|alignat|aligned|alignedat|array|Bmatrix|bmatrix|cases|CD|eqnarray|equation|gather|gathered|matrix|multline|pmatrix|smallmatrix|split|subarray|Vmatrix|vmatrix)\*?)\}</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>keyword.command.latex</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>variable.parameter.identifier.latex</string>
                            </dict>
                        </dict>
                        <key>endCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>keyword.command.latex</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>variable.parameter.identifier.latex</string>
                            </dict>
                        </dict>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>$self</string>
                            </dict>
                            <dict>
                                <key>name</key>
                                <string>string.math.latex</string>
                                <key>match</key>
                                <string>[^\$%\{\}\[\]\\\s]+</string>
                            </dict>
                        </array>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>(\\(?:documentclass|usepackage|begin|end))\[?</string>
                        <key>end</key>
                        <string>\]?(?:\{([^\$%\{\}\[\]\\\s]*)\})</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>keyword.command.latex</string>
                            </dict>
                        </dict>
                        <key>endCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>variable.parameter.identifier.latex</string>
                            </dict>
                        </dict>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>$self</string>
                            </dict>
                            <dict>
                                <key>name</key>
                                <string>entity.name.type.options.latex</string>
                                <key>match</key>
                                <string>[^\$%\{\}\[\]\\\s]+</string>
                            </dict>
                        </array>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>(\\(?:chapter|(?:sub){0,2}section|(?:sub)?paragraph)\*?)\{</string>
                        <key>end</key>
                        <string>\}</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>keyword.command.latex</string>
                            </dict>
                        </dict>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>$self</string>
                            </dict>
                            <dict>
                                <key>name</key>
                                <string>entity.name.type.section.latex</string>
                                <key>match</key>
                                <string>[^\$%\{\}\[\]\\\s]+</string>
                            </dict>
                        </array>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.latex</string>
                        <key>match</key>
                        <string>\\[#\$%&amp;_{}~\\,]</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.command.latex</string>
                        <key>match</key>
                        <string>\\[a-zA-Z@]+(\*)?</string>
                    </dict>
                </array>
            </dict>
            <key>math</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>string.math.latex</string>
                        <key>begin</key>
                        <string>(\$\$|\\\[)</string>
                        <key>end</key>
                        <string>(\$\$|\\\])</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>$self</string>
                            </dict>
                        </array>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>string.math.latex</string>
                        <key>begin</key>
                        <string>(\$|\\\()</string>
                        <key>end</key>
                        <string>(\$|\\\))</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>$self</string>
                            </dict>
                        </array>
                    </dict>
                </array>
            </dict>
        </dict>
    </dict>
</plist>
